#!/usr/bin/env bash
# One-shot packet. Checked-in release basis is DRAFT_NOT_RELEASED, so it fails closed.
set -Eeuo pipefail
umask 077
REPO=/home/holden/mckernel; SB=/home/holden/mckernel-work/scratch; E=$SB/native-exact-cleanup-execution-68cf089a-1
C=/dev/shm/mckernel-exact-candidate-68cf089a-1; B=/dev/shm/mckernel-exact-metadata-backup-68cf089a-1; QC=/dev/shm/.mckernel-quarantine-mckernel-exact-candidate-68cf089a-1; QB=/dev/shm/.mckernel-quarantine-mckernel-exact-metadata-backup-68cf089a-1
LEASE=$SB/native-exact-build-lease-68cf089a-1.json; JOURNAL=$SB/native-exact-candidate-delete-68cf089a-1.journal.jsonl; PREFLIGHT=$SB/native-exact-candidate-delete-preflight-68cf089a-1.json; RELEASE=$SB/native-exact-candidate-delete-release-68cf089a-1.json; POST_OUT=$SB/native-exact-live-reference-post-seal-68cf089a-1.stdout.json; POST_ERR=$SB/native-exact-live-reference-post-seal-68cf089a-1.stderr.txt
OBSERVER=$REPO/docs/verification/evidence/native-exact-candidate-live-reference-observer-68cf089a-1.py; DELETER=$REPO/docs/verification/evidence/native-exact-candidate-delete-68cf089a-1.py; GENERATOR=$REPO/scripts/native_rust_exact_candidate_inventory.py; INVENTORY=$SB/native-exact-complete-worktree-inventory-68cf089a-1.json; INV_ARCHIVE=$REPO/docs/verification/evidence/stability-native-exact-complete-inventory-68cf089a-20260929-1.tar.gz; RET=$REPO/docs/verification/evidence/stability-native-exact-prepared-candidate-retention-68cf089a-20260929-1.tar.gz; PREP=$REPO/docs/verification/evidence/stability-native-exact-candidate-preparation-68cf089a-20260929-1.tar.gz; PREP_RECORD=$REPO/docs/verification/stability-native-exact-candidate-preparation-checkpoint-20260929-1.json; RET_RECORD=$REPO/docs/verification/evidence/stability-native-exact-prepared-candidate-retention-20260929-1.json; INPUTS=$SB/native-exact-inputs-68cf089a-1.json; REQUEST=$SB/native-exact-build-request-68cf089a-1.json; BASIS=$REPO/docs/verification/evidence/native-exact-candidate-cleanup-release-basis-68cf089a-1.json
SOURCE_CHECKPOINT=7e008f468932c016e1768e29867271f325d642ab; STAGING_REF=origin/codex/local-native-staging-repair
TEMPLATE_SHA=3803cf64023f06a030a795a7c035177f0dd32563efd660ba3dde4e36f4fe1eb0; OBSERVER_SHA=4a15271df7e14f1a95136579f157f0fc719048143547be6a54a242b99c3f8e05; GEN_SHA=ed2c2eaf1200da67625ed3438d4790c55f6dbf60f9ba105505c7df8807bf1678; INVENTORY_SHA=743c05648112cee5af2eda235fba11a2f32d50a9d3074423c0c064d52a1682c0; INV_ARCHIVE_SHA=6be734da7ee54eec0523fa961a0264b5242637c26d56952f524b84c907f0b044; RET_SHA=eed1879bd35c62d7aa629189dfc0c46254680209ab02f933278c70c8cf9880c6; PREP_SHA=78e2b5c44e9ae00f2f463ac8b93723e26d00877fbbe7ecfb285d1d89d6404264; PREP_RECORD_SHA=bc8b3a6d819208b7266e39bb91862ddbacba5ec700dcf14b960fe7857aa2be99; RET_RECORD_SHA=129d25f80a29fc321cae94c3e1f4db4279e42c1b100ea41c6406a3a3e133f7b6; INPUTS_SHA=ae0c5f74e3e3f06176c46f2f174b1109c11a4e88f23ee71fd7432e6325262abd; REQUEST_SHA=25f820e2994d41427ed16cf5f062d647125ccb7144f63afe618e88ccce7f576c
FINAL_DELETER_SHA=__REPLACE_WITH_FINAL_DELETER_SHA256__; RELEASE_SHA=__REPLACE_WITH_RELEASE_SHA256__
die(){ echo "FAIL-CLOSED: $*" >&2; exit 1; }; sha(){ /usr/bin/sha256sum -- "$1" | /usr/bin/awk '{print $1}'; }; genv=(/usr/bin/env -i PATH=/usr/bin:/bin HOME=/nonexistent LANG=C LC_ALL=C GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null GIT_NO_REPLACE_OBJECTS=1 GIT_TERMINAL_PROMPT=0 GIT_ALLOW_PROTOCOL=file)
[[ ${EUID:-1} -ne 0 && "$FINAL_DELETER_SHA" =~ ^[0-9a-f]{64}$ && "$RELEASE_SHA" =~ ^[0-9a-f]{64}$ ]] || die pins-or-root
[[ ! -e "$E" ]] || die evidence-exists; /usr/bin/mkdir -m700 "$E"; LOG=$E/outer.log; set -C; : >"$LOG"; set +C; exec >>"$LOG" 2>&1
[[ ! -e "$LEASE" && ! -e "$JOURNAL" && ! -e "$PREFLIGHT" && ! -e "$RELEASE" && ! -e "$POST_OUT" && ! -e "$POST_ERR" && ! -e "$QC" && ! -e "$QB" ]] || die stale-state
for p in "$OBSERVER" "$DELETER" "$GENERATOR" "$INVENTORY" "$INV_ARCHIVE" "$RET" "$PREP" "$PREP_RECORD" "$RET_RECORD" "$INPUTS" "$REQUEST" "$BASIS"; do [[ -f "$p" && ! -L "$p" ]] || die missing-input; done
gitcap(){ local n=$1; shift; if ! "${genv[@]}" /usr/bin/git "$@" >"$E/$n" 2>"$E/$n.err"; then die "git-failed:$n"; fi; }
gitcap head -C "$REPO" rev-parse --verify HEAD; gitcap staging -C "$REPO" rev-parse --verify "$STAGING_REF"; [[ "$(<"$E/head")" == "$(<"$E/staging")" ]] || die head-not-staging
if ! "${genv[@]}" /usr/bin/git -C "$REPO" merge-base --is-ancestor "$SOURCE_CHECKPOINT" HEAD >"$E/ancestor" 2>"$E/ancestor.err"; then die source-not-ancestor; fi
blob(){ local p=$1 h=$2 n=$3; if ! "${genv[@]}" /usr/bin/git -C "$REPO" show "$SOURCE_CHECKPOINT:$p" >"$E/$n" 2>"$E/$n.err"; then die git-show; fi; [[ "$(sha "$E/$n")" == "$h" ]] || die fetched-blob; }
blob docs/verification/evidence/native-exact-candidate-delete-68cf089a-1.py "$TEMPLATE_SHA" template-deleter; blob docs/verification/evidence/native-exact-candidate-live-reference-observer-68cf089a-1.py "$OBSERVER_SHA" template-observer; blob scripts/native_rust_exact_candidate_inventory.py "$GEN_SHA" template-generator; blob docs/verification/evidence/stability-native-exact-complete-inventory-68cf089a-20260929-1.tar.gz "$INV_ARCHIVE_SHA" template-inventory-archive
[[ "$(sha "$DELETER")" == "$FINAL_DELETER_SHA" && "$(sha "$OBSERVER")" == "$OBSERVER_SHA" ]] || die local-helper-pin
for pair in "$INVENTORY:$INVENTORY_SHA" "$INV_ARCHIVE:$INV_ARCHIVE_SHA" "$RET:$RET_SHA" "$PREP:$PREP_SHA" "$PREP_RECORD:$PREP_RECORD_SHA" "$RET_RECORD:$RET_RECORD_SHA" "$INPUTS:$INPUTS_SHA" "$REQUEST:$REQUEST_SHA"; do p=${pair%%:*}; h=${pair##*:}; [[ "$(sha "${!p}")" == "$h" ]] || die input-hash; done
/usr/bin/python3 -c 'import tarfile,hashlib,os,sys;a,l=sys.argv[1:]; d=hashlib.sha256(open(l,"rb").read()).digest(); t=tarfile.open(a); m=[x for x in t.getmembers() if x.isfile() and os.path.basename(x.name)==os.path.basename(l)]; sys.exit(not(len(m)==1 and hashlib.sha256(t.extractfile(m[0]).read()).digest()==d))' "$INV_ARCHIVE" "$INVENTORY" || die inventory-archive
/usr/bin/python3 -c 'import os,sys,json; s=os.statvfs(sys.argv[1]); h=os.statvfs("/"); r=os.statvfs("/dev/shm"); open(sys.argv[2],"w").write(json.dumps({"host":h.f_bavail*h.f_frsize,"scratch":s.f_bavail*s.f_frsize,"tmpfs":r.f_bavail*r.f_frsize})+"\n"); sys.exit(h.f_bavail*h.f_frsize<16<<30 or s.f_bavail*s.f_frsize<12<<30 or r.f_bavail*r.f_frsize<64<<20)' "$SB" "$E/capacity.json" || die capacity
/usr/bin/python3 -c 'import os,stat,sys; p,d,i,n=sys.argv[1:]; s=os.lstat(p); st=[p]; q=set(); exec("while st:\n x=st.pop(); y=os.lstat(x); q.add((y.st_dev,y.st_ino));\n if stat.S_ISDIR(y.st_mode):\n  with os.scandir(x) as z: st.extend(e.path for e in z)"); sys.exit(not(stat.S_ISDIR(s.st_mode) and (s.st_dev,s.st_ino,stat.S_IMODE(s.st_mode))==(int(d),int(i),0o755) and len(q)==int(n)))' "$C" 26 14117 10462 || die candidate-root
/usr/bin/python3 -c 'import os,stat,sys; p,d,i,n=sys.argv[1:]; s=os.lstat(p); st=[p]; q=set(); exec("while st:\n x=st.pop(); y=os.lstat(x); q.add((y.st_dev,y.st_ino));\n if stat.S_ISDIR(y.st_mode):\n  with os.scandir(x) as z: st.extend(e.path for e in z)"); sys.exit(not(stat.S_ISDIR(s.st_mode) and (s.st_dev,s.st_ino,stat.S_IMODE(s.st_mode))==(int(d),int(i),0o755) and len(q)==int(n)))' "$B" 26 24701 87 || die backup-root
/usr/bin/ps -eo pid=,ppid=,args= >"$E/processes.txt" || die ps; /usr/bin/python3 -c 'import re,sys;sys.exit(any(re.search(r"(^|[ /])(qemu-system|qemu-kvm|mcexec|native-rust-exact)(?:[ /]|$)",x) for x in open(sys.argv[1],errors="replace")))' "$E/processes.txt" || die active-owner
if ! /usr/bin/sudo -A /usr/bin/env -i PATH=/usr/bin:/bin HOME=/nonexistent /usr/bin/docker ps --filter status=running --no-trunc --format '{{json .}}' >"$E/docker-running.jsonl"; then die docker-ps; fi
/usr/bin/python3 -c 'import json,sys;open(sys.argv[2],"w").write("".join(json.loads(x)["ID"]+"\n" for x in open(sys.argv[1]) if x.strip()))' "$E/docker-running.jsonl" "$E/docker-ids"
while IFS= read -r id; do [[ -z "$id" ]] || /usr/bin/sudo -A /usr/bin/env -i PATH=/usr/bin:/bin HOME=/nonexistent /usr/bin/docker inspect "$id" >>"$E/docker-inspect.jsonl" || die docker-inspect; done <"$E/docker-ids"
/usr/bin/python3 -c 'import json,os,sys;t=[os.path.normpath(x) for x in sys.argv[2:]]; z=open(sys.argv[1]).read(); d=json.JSONDecoder(); i=0
while i<len(z):
 while i<len(z) and z[i].isspace(): i+=1
 if i==len(z): break
 x,i=d.raw_decode(z,i)
 for c in x if isinstance(x,list) else [x]:
  for m in c.get("Mounts",[]):
   for v in (m.get("Source"),m.get("Destination")):
    if isinstance(v,str):
     v=os.path.normpath(v)
     if any(v==q or v.startswith(q+os.sep) or q.startswith(v+os.sep) for q in t): raise SystemExit(1)' "$E/docker-inspect.jsonl" "$C" "$B" "$QC" "$QB" || die docker-bind
/usr/bin/python3 -c 'import json,sys;x=json.load(open(sys.argv[1]));sys.exit(not(x.get("status")=="PASS_ONE_SHOT_CLEANUP" and not x.get("final_deleter_sha256","").startswith("UNSET") and not x.get("release_record_sha256","").startswith("UNSET")))' "$BASIS" || die draft-basis
die 'basis-PASS packet must be independently substituted with O_EXCL canonical release/preflight writers; checked-in packet intentionally stops before mutation'
