#!/bin/sh

# Ensure that strace tests kernel PTRACE_O_TRACECLONE
# and PTRACE_O_TRACESYSGOOD support properly.

. "${srcdir=.}/init.sh"

[ "$(uname -s)" = Linux ] ||
	skip_ 'The kernel is not a Linux kernel'
case "$(uname -r)" in
	2.[6-9]*|2.[1-5][0-9]*|[3-9].*|[12][0-9]*) ;;
	*) skip_ 'The kernel is not Linux 2.6.* or newer' ;;
esac

check_strace
check_timeout

$TIMEOUT $MCEXEC $STRACE -df -enone / 2>&1 |
	grep -E -x '(.+: )?ptrace_setoptions = (0xe|0x5f)' > /dev/null ||
		fail_ 'strace -f failed to recognize proper kernel PTRACE_O_TRACECLONE support'
echo ptrace_setoptions-1 OK

$TIMEOUT $MCEXEC $STRACE -df -enone / 2>&1 |
	grep -E -x '(.+: )?ptrace_setoptions = (0x1f|0x5f)' > /dev/null ||
		fail_ 'strace -f failed to recognize proper kernel PTRACE_O_TRACESYSGOOD support'
echo ptrace_setoptions-2 OK

$TIMEOUT $MCEXEC $STRACE -d -enone / 2>&1 |
	grep -E -x '(.+: )?ptrace_setoptions = (0x11|0x51)' > /dev/null ||
		fail_ 'strace failed to recognize proper kernel PTRACE_O_TRACESYSGOOD support'
echo ptrace_setoptions-3 OK
