// SPDX-License-Identifier: (BSD-2-Clause OR GPL-2.0)
//! Native Rust-for-Linux x86_64 IHK SMP module lifecycle.
//!
//! Linux 6.12 does not yet expose module parameters through its Rust
//! `module!` macro.  The six frozen legacy parameters therefore use the same
//! `__param` ABI as `module_param()`, backed by the kernel's exported numeric
//! parameter operations.  Linux's `MODULE_PARAM_PREFIX` is empty for a
//! loadable module and `KBUILD_MODNAME.` for a built-in, so both descriptor
//! names are emitted explicitly.  No project-owned C object participates in
//! this crate.

use kernel::{
    c_str,
    miscdevice::{MiscDevice, MiscDeviceOptions, MiscDeviceRegistration},
    prelude::*,
};

// Reuse the resource policy in the Linux CPU and memory adapters, including
// generation-checked OS assignment. IKC and boot integration remain pending;
// unused policy surfaces stay private.
#[allow(dead_code)]
mod smp_resource;
mod smp_cpu;
mod smp_memory;
// Reuse the existing checked mapping geometry for owned image destinations.
#[allow(dead_code)]
mod ihk_mapping;
#[allow(dead_code)]
mod smp_image;
mod smp_loader;
mod smp_startup;
mod smp_trampoline;
mod smp_boot_code;
#[allow(dead_code, unreachable_pub)]
#[path = "abi/x86_64.rs"]
mod abi;
#[allow(dead_code)]
mod ikc_queue;
#[allow(dead_code)]
mod ikc_master;
mod smp_ikc;

const IHK_SMP_PARAMETER_COUNT: usize = 6;
const IHK_SMP_DEPENDENCY: &str = "ihk";
const IHK_SMP_IMPORT_NAMESPACE: &str = "MCKERNEL_IHK_V1";
const IHK_SMP_PROVIDER_CALLBACK_ABI_V1: u32 = 1;
const IHK_SMP_PROVIDER_FLAG_SHARED: u32 = 1;
const IHK_SMP_CONTROL_DEVICE_MINOR: u32 = 0;

const IHK_DEVICE_GET_BUILDID: u32 = 0x0011_290b;
const IHK_DEVICE_CREATE_OS: u32 = 0x0011_2900;
const IHK_DEVICE_DESTROY_OS: u32 = 0x0011_2901;
// Generated by the authoritative stager from the unchanged IHK consumers'
// BUILDID rule.  Those consumers allocate sizeof(BUILDID), so this payload
// must retain their exact bytes and trailing NUL.  Native source provenance
// is recorded separately in stage-lock.json, not substituted into this UAPI.
const IHK_COMPAT_BUILD_ID: &[u8] = include_bytes!("ihk-compat-build-id.bin");

fn control_device_ioctl(cmd: u32, arg: usize) -> Result<isize> {
    match cmd {
        IHK_DEVICE_GET_BUILDID => {
            kernel::uaccess::UserSlice::new(arg, IHK_COMPAT_BUILD_ID.len())
                .writer()
                .write_slice(IHK_COMPAT_BUILD_ID)?;
            Ok(0)
        }
        _ => Err(EINVAL),
    }
}

fn control_device_request(cmd: u32, arg: usize) -> Result<isize> {
    match cmd {
        IHK_DEVICE_CREATE_OS => {
            // SAFETY: This callback runs with the SMP control file pinning
            // THIS_MODULE. IHK acquires its own module reference before the
            // instance becomes live; the raw scalar argument is never a pointer.
            let result = unsafe {
                ihk_os_create_unbooted_v3(
                    IHK_SMP_CONTROL_DEVICE_MINOR,
                    THIS_MODULE.as_ptr().cast(),
                    arg as u64,
                    1,
                    Some(ihk_smp_os_ioctl_v2),
                    Some(ihk_smp_os_release_v2),
                    Some(ihk_smp_prepare_boot_v3),
                    Some(ihk_smp_start_boot_v3),
                )
            };
            if result < 0 {
                Err(provider_status_error(result))
            } else {
                Ok(result as isize)
            }
        }
        IHK_DEVICE_DESTROY_OS => {
            // SAFETY: IHK owns this scalar ABI for the dependency lifetime.
            // It validates the provider and minor and refuses open instances.
            let result =
                unsafe { ihk_os_destroy_unbooted_v1(IHK_SMP_CONTROL_DEVICE_MINOR, arg as u64) };
            if result < 0 {
                Err(provider_status_error(result))
            } else {
                Ok(result as isize)
            }
        }
        _ => control_device_ioctl(cmd, arg),
    }
}

// SAFETY: This scalar C-ABI callback borrows no provider or caller memory.
type IhkSmpProviderInitV2 = extern "C" fn() -> i32;
// SAFETY: This scalar C-ABI callback borrows no provider or caller memory.
type IhkSmpProviderExitV2 = extern "C" fn();

// SAFETY: IHK holds the exact OS lease, operation lock and SMP module owner.
// The address and compat flag are borrowed only during the synchronous call.
type IhkSmpOsIoctlV2 = unsafe extern "C" fn(u32, u64, u32, u64, u32) -> i64;
// SAFETY: IHK holds the exclusive initial-state destruction guard and module
// owner until this callback returns all resources or leaves them unchanged.
type IhkSmpOsReleaseV2 = unsafe extern "C" fn(u32, u64) -> i32;
// SAFETY: IHK supplies its own live kmsg physical address and allocation size.
// Preparation cannot start CPUs or publish guest work into Linux queues.
type IhkSmpPrepareBootV3 = unsafe extern "C" fn(u32, u64, u64, u64) -> i32;
// SAFETY: IHK publishes Booting first and retains owners after any start result.
type IhkSmpStartBootV3 = unsafe extern "C" fn(u32, u64) -> i32;

// SAFETY: The provider owns these namespaced symbols for its full module
// lifetime.  The byte is read-only; the C-ABI functions exchange only scalars
// and scalar-only callback function identities. The OS-create call also borrows
// the pinned caller's Linux module pointer; no private Rust object crosses it.
extern "C" {
    #[link_name = "ihk_provider_lifecycle_v1"]
    static IHK_PROVIDER_LIFECYCLE_V1: u8;
    #[link_name = "ihk_smp_provider_attach_v2"]
    fn ihk_smp_provider_attach_v2(
        callback_abi: u32,
        flags: u32,
        init: Option<IhkSmpProviderInitV2>,
        exit: Option<IhkSmpProviderExitV2>,
    ) -> i64;
    #[link_name = "ihk_smp_provider_detach_v2"]
    fn ihk_smp_provider_detach_v2(token: i64, exit: Option<IhkSmpProviderExitV2>);
    #[link_name = "ihk_smp_provider_open_v1"]
    fn ihk_smp_provider_open_v1(minor: u32) -> i64;
    #[link_name = "ihk_smp_provider_close_v1"]
    fn ihk_smp_provider_close_v1(receipt: i64);
    #[link_name = "ihk_os_create_unbooted_v3"]
    fn ihk_os_create_unbooted_v3(
        provider_minor: u32,
        owner: *mut core::ffi::c_void,
        argument: u64,
        callback_abi: u32,
        ioctl: Option<IhkSmpOsIoctlV2>,
        release: Option<IhkSmpOsReleaseV2>,
        prepare: Option<IhkSmpPrepareBootV3>,
        start: Option<IhkSmpStartBootV3>,
    ) -> i64;
    #[link_name = "ihk_os_destroy_unbooted_v1"]
    fn ihk_os_destroy_unbooted_v1(provider_minor: u32, minor: u64) -> i64;
}

// SAFETY: Only IHK's versioned OS object invokes this registered callback. It
// holds an OsLease for the exact slot/generation, its sleepable operation lock,
// and the owning SMP module reference. User pointers live only for this call.
unsafe extern "C" fn ihk_smp_os_ioctl_v2(
    slot: u32,
    generation: u64,
    command: u32,
    argument: u64,
    compat: u32,
) -> i64 {
    if compat > 1 || (compat == 1 && argument > u32::MAX as u64) {
        return EINVAL.to_errno() as i64;
    }
    // SAFETY: IHK supplies the live lease proof described by this callback ABI;
    // these identifiers are not derived from the user's ioctl arguments.
    let owner = match unsafe { smp_resource::OsToken::from_ihk_lease_v2(slot, generation) } {
        Ok(owner) => owner,
        Err(_) => return EINVAL.to_errno() as i64,
    };
    let result = if command == 0x0011_2a00 {
        smp_loader::load(owner, argument as usize)
    } else if command == abi::IHK_OS_SET_KARGS {
        smp_memory::set_kernel_arguments(owner, argument as usize)
    } else if smp_cpu::handles_os(command) {
        smp_cpu::os_ioctl(owner, command, argument as usize, compat == 1)
    } else if smp_memory::handles_os(command) {
        smp_memory::os_ioctl(owner, command, argument as usize, compat == 1)
    } else {
        Err(EINVAL)
    };
    match result {
        Ok(value) => value as i64,
        Err(error) => error.to_errno() as i64,
    }
}

// SAFETY: IHK invokes this only with the exclusive initial-state DestroyGuard
// and the retained SMP module owner. No OS file, boot, or other resource call
// can overlap cleanup for this generation. Errors leave its resources intact.
unsafe extern "C" fn ihk_smp_os_release_v2(slot: u32, generation: u64) -> i32 {
    // SAFETY: The versioned IHK exclusive destruction callback proves the
    // exact generation remains owned until both resource maps are cleaned up.
    let owner = match unsafe { smp_resource::OsToken::from_ihk_lease_v2(slot, generation) } {
        Ok(owner) => owner,
        Err(_) => return EINVAL.to_errno(),
    };
    match smp_cpu::release_os_resources(owner) {
        Ok(()) => 0,
        Err(error) => error.to_errno(),
    }
}

// SAFETY: IHK holds its exact OS lease, per-OS operation mutex and SMP module
// owner. kmsg scalars identify IHK's allocation, never an ioctl user pointer.
unsafe extern "C" fn ihk_smp_prepare_boot_v3(
    slot: u32,
    generation: u64,
    kmsg: u64,
    kmsg_bytes: u64,
) -> i32 {
    // SAFETY: The v3 callback retains the same trusted IHK generation proof.
    let owner = match unsafe { smp_resource::OsToken::from_ihk_lease_v2(slot, generation) } {
        Ok(owner) => owner,
        Err(_) => return EINVAL.to_errno(),
    };
    // SAFETY: The diagnostic parameter is read-only after module init.
    let prepare_only = unsafe { NATIVE_BOOT_PREPARE_ONLY };
    if prepare_only > 1 {
        return EINVAL.to_errno();
    }
    // SAFETY: Reuse the existing writable ihk_trampoline parameter. Linux's
    // parameter mutex excludes concurrent sysfs writes during this scalar
    // snapshot; no parameter lock crosses resource locking or CPU startup.
    let trampoline = unsafe {
        kernel::bindings::kernel_param_lock(THIS_MODULE.as_ptr());
        let value = core::ptr::read_volatile(&raw const IHK_TRAMPOLINE);
        kernel::bindings::kernel_param_unlock(THIS_MODULE.as_ptr());
        value
    };
    match smp_cpu::prepare_os_boot(owner, kmsg, kmsg_bytes, trampoline) {
        Ok(()) if prepare_only == 1 => {
            pr_info!("IHK-SMP: boot preparation held os={} generation={}; diagnostic mode, CPUs not started\n", slot, generation);
            -11
        }
        Ok(()) => 0,
        Err(error) => error.to_errno(),
    }
}

// SAFETY: IHK has already published Booting and excludes resource mutation.
// The native adapter retains every owner before the first CPU-start effect.
unsafe extern "C" fn ihk_smp_start_boot_v3(slot: u32, generation: u64) -> i32 {
    // SAFETY: The v3 start callback carries the same exact-generation lease.
    let owner = match unsafe { smp_resource::OsToken::from_ihk_lease_v2(slot, generation) } {
        Ok(owner) => owner,
        Err(_) => return EINVAL.to_errno(),
    };
    match smp_cpu::start_os_boot(owner) {
        Ok(()) => 0,
        Err(error) => error.to_errno(),
    }
}

// These callbacks deliberately own lifecycle only.  Returning success from
// init does not advertise any device operation, OS lease, CPU, memory, IKC, or
// McKernel behavior.  The IHK provider invokes them before publication and
// while holding an unpublishing guard respectively.
// SAFETY: The callback owns no foreign state and returns only a literal errno
// status through the exact v2 function-pointer ABI.
extern "C" fn ihk_smp_provider_init_v2() -> i32 {
    pr_info!("provider_callback=init status=complete callback_abi=1\n");
    0
}

// SAFETY: The callback owns no foreign state and returns only after its local
// lifecycle diagnostic completes through the exact v2 function-pointer ABI.
extern "C" fn ihk_smp_provider_exit_v2() {
    pr_info!("provider_callback=exit status=complete callback_abi=1\n");
}

fn provider_status_error(status: i64) -> Error {
    let errno = match status {
        -2 | -12 | -16 | -19 | -22 | -75 | -116 | -117 => status as i32,
        _ => -117,
    };
    match kernel::error::to_result(errno) {
        Err(error) => error,
        Ok(()) => EIO,
    }
}

#[must_use = "the provider lease must remain owned until SMP module teardown"]
struct ProviderLease {
    token: i64,
}

impl ProviderLease {
    fn attach() -> Result<Self> {
        // SAFETY: ihk.ko owns the exact namespaced C-ABI function for the
        // dependency lifetime.  The exact callbacks accept no arguments, own
        // no caller memory, and remain resident until the matching detach.
        let token = unsafe {
            ihk_smp_provider_attach_v2(
                IHK_SMP_PROVIDER_CALLBACK_ABI_V1,
                IHK_SMP_PROVIDER_FLAG_SHARED,
                Some(ihk_smp_provider_init_v2),
                Some(ihk_smp_provider_exit_v2),
            )
        };
        if token <= 0 {
            return Err(provider_status_error(token));
        }
        Ok(Self { token })
    }
}

impl Drop for ProviderLease {
    fn drop(&mut self) {
        // SAFETY: This non-Copy owner calls the matching provider function
        // exactly once with the positive token returned by attach and the
        // retained exit identity.  The provider fails stop rather than
        // returning with a live entry or callback.
        unsafe { ihk_smp_provider_detach_v2(self.token, Some(ihk_smp_provider_exit_v2)) };
    }
}

#[must_use = "the provider-open receipt must remain owned until file release"]
struct ProviderOpenLease {
    receipt: i64,
}

impl ProviderOpenLease {
    fn acquire() -> Result<Self> {
        // SAFETY: ihk.ko owns this exact namespaced scalar function for the
        // dependency lifetime.  Minor zero is the only published provider
        // slot in this bounded shell, and no pointer or Rust layout crosses
        // the boundary.
        let receipt = unsafe { ihk_smp_provider_open_v1(IHK_SMP_CONTROL_DEVICE_MINOR) };
        if receipt <= 0 {
            return Err(provider_status_error(receipt));
        }
        Ok(Self { receipt })
    }
}

impl Drop for ProviderOpenLease {
    fn drop(&mut self) {
        // SAFETY: This non-Copy per-file owner calls the matching scalar close
        // exactly once with the positive opaque receipt returned by open.  The
        // shared scalar is not a unique per-file identity, so this trusted
        // non-Copy wrapper is the count-balance authority.  ihk.ko fails stop
        // on a nonpositive, stale, or zero-reference release.
        unsafe { ihk_smp_provider_close_v1(self.receipt) };
    }
}

struct IhkSmpControlDevice;

#[vtable]
impl MiscDevice for IhkSmpControlDevice {
    type Ptr = Box<ProviderOpenLease>;

    const MODULE: &'static ThisModule = &THIS_MODULE;

    fn open() -> Result<Self::Ptr> {
        // Linux 6.12's `BoxExt::new` takes ownership before allocation.  If
        // allocation fails, the temporary ProviderOpenLease is dropped and
        // closes the already-acquired scalar receipt before ENOMEM is returned.
        Box::new(ProviderOpenLease::acquire()?, GFP_KERNEL).map_err(|_| ENOMEM)
    }

    fn ioctl(_device: &ProviderOpenLease, cmd: u32, arg: usize) -> Result<isize> {
        if smp_cpu::handles(cmd) {
            return smp_cpu::ioctl(cmd, arg, false);
        }
        if smp_memory::handles(cmd) {
            return smp_memory::ioctl(cmd, arg, false);
        }
        control_device_request(cmd, arg)
    }

    #[cfg(CONFIG_COMPAT)]
    fn compat_ioctl(_device: &ProviderOpenLease, cmd: u32, arg: usize) -> Result<isize> {
        if smp_cpu::handles(cmd) {
            return smp_cpu::ioctl(cmd, arg as u32 as usize, true);
        }
        if smp_memory::handles(cmd) {
            return smp_memory::ioctl(cmd, arg as u32 as usize, true);
        }
        // This command takes a userspace pointer.  On x86_64 compat callers
        // supply a 32-bit address; zero extension matches compat_ptr().
        control_device_request(cmd, arg as u32 as usize)
    }
}

// This is the x86_64 layout of Linux 6.12's `struct kernel_param`.  Keeping a
// local representation avoids depending on bindgen's unstable anonymous-union
// field name while the size/alignment checks below bind it to the generated
// Rocky kernel type.
#[repr(C)]
union KernelParameterValue {
    arg: *mut core::ffi::c_void,
}

#[repr(C)]
struct KernelParameter {
    name: *const core::ffi::c_char,
    module: *mut kernel::bindings::module,
    ops: *const kernel::bindings::kernel_param_ops,
    permission: u16,
    level: i8,
    flags: u8,
    value: KernelParameterValue,
}

// SAFETY: Each instance is immutable after relocation.  Linux owns access to
// the pointed-to parameter storage and serializes writes with its parameter
// subsystem; the used trampoline value is read under that same mutex.
unsafe impl Sync for KernelParameter {}

const _: [(); core::mem::size_of::<kernel::bindings::kernel_param>()] =
    [(); core::mem::size_of::<KernelParameter>()];
const _: [(); core::mem::align_of::<kernel::bindings::kernel_param>()] =
    [(); core::mem::align_of::<KernelParameter>()];

macro_rules! numeric_parameter {
    (
        name: $name:ident,
        storage: $storage:ident,
        descriptor: $descriptor:ident,
        rust_type: $rust_type:ty,
        ops: $ops:ident,
        default: $default:literal,
        permission: $permission:literal,
        loadable_name_bytes: $loadable_name_bytes:literal,
        builtin_name_bytes: $builtin_name_bytes:literal,
    ) => {
        #[doc(hidden)]
        // SAFETY: Linux's parameter subsystem is the only writer after module
        // publication and serializes access; Rust never reads this storage.
        static mut $storage: $rust_type = $default;

        #[doc(hidden)]
        #[link_section = "__param"]
        #[used(compiler)]
        static $descriptor: KernelParameter = KernelParameter {
            name: {
                #[cfg(MODULE)]
                const PARAMETER_NAME: &[u8] = $loadable_name_bytes;
                #[cfg(not(MODULE))]
                const PARAMETER_NAME: &[u8] = $builtin_name_bytes;
                PARAMETER_NAME.as_ptr() as *const core::ffi::c_char
            },
            module: THIS_MODULE.as_ptr(),
            // `param_ops_uint` and `param_ops_ulong` are immutable, exported
            // Linux kernel objects with static lifetime.
            ops: core::ptr::addr_of!(kernel::bindings::$ops),
            permission: $permission,
            level: -1,
            flags: 0,
            value: KernelParameterValue {
                arg: core::ptr::addr_of_mut!($storage) as *mut core::ffi::c_void,
            },
        };

        // Make the contract name part of the expansion even though the ABI
        // consumes its explicitly NUL-terminated byte form above.
        const _: &str = stringify!($name);
    };
}

numeric_parameter!(
    name: ihk_phys_start,
    storage: IHK_PHYS_START,
    descriptor: PARAM_IHK_PHYS_START,
    rust_type: core::ffi::c_ulong,
    ops: param_ops_ulong,
    default: 0,
    permission: 0o644,
    loadable_name_bytes: b"ihk_phys_start\0",
    builtin_name_bytes: b"ihk_smp_x86_64.ihk_phys_start\0",
);

// Additive read-only diagnostic parameter; the six legacy parameters retain
// their ABI. A held preparation returns EAGAIN and never claims a boot success.
numeric_parameter!(
    name: native_boot_prepare_only,
    storage: NATIVE_BOOT_PREPARE_ONLY,
    descriptor: PARAM_NATIVE_BOOT_PREPARE_ONLY,
    rust_type: core::ffi::c_uint,
    ops: param_ops_uint,
    default: 0,
    permission: 0o400,
    loadable_name_bytes: b"native_boot_prepare_only\0",
    builtin_name_bytes: b"ihk_smp_x86_64.native_boot_prepare_only\0",
);

numeric_parameter!(
    name: ihk_mem,
    storage: IHK_MEM,
    descriptor: PARAM_IHK_MEM,
    rust_type: core::ffi::c_ulong,
    ops: param_ops_ulong,
    default: 0,
    permission: 0o644,
    loadable_name_bytes: b"ihk_mem\0",
    builtin_name_bytes: b"ihk_smp_x86_64.ihk_mem\0",
);

numeric_parameter!(
    name: ihk_cores,
    storage: IHK_CORES,
    descriptor: PARAM_IHK_CORES,
    rust_type: core::ffi::c_uint,
    ops: param_ops_uint,
    default: 0,
    permission: 0o644,
    loadable_name_bytes: b"ihk_cores\0",
    builtin_name_bytes: b"ihk_smp_x86_64.ihk_cores\0",
);

numeric_parameter!(
    name: ihk_start_irq,
    storage: IHK_START_IRQ,
    descriptor: PARAM_IHK_START_IRQ,
    rust_type: core::ffi::c_uint,
    ops: param_ops_uint,
    default: 0,
    permission: 0o644,
    loadable_name_bytes: b"ihk_start_irq\0",
    builtin_name_bytes: b"ihk_smp_x86_64.ihk_start_irq\0",
);

numeric_parameter!(
    name: ihk_ikc_irq_core,
    storage: IHK_IKC_IRQ_CORE,
    descriptor: PARAM_IHK_IKC_IRQ_CORE,
    rust_type: core::ffi::c_uint,
    ops: param_ops_uint,
    default: 0,
    permission: 0o644,
    loadable_name_bytes: b"ihk_ikc_irq_core\0",
    builtin_name_bytes: b"ihk_smp_x86_64.ihk_ikc_irq_core\0",
);

numeric_parameter!(
    name: ihk_trampoline,
    storage: IHK_TRAMPOLINE,
    descriptor: PARAM_IHK_TRAMPOLINE,
    rust_type: core::ffi::c_ulong,
    ops: param_ops_ulong,
    default: 0,
    permission: 0o644,
    loadable_name_bytes: b"ihk_trampoline\0",
    builtin_name_bytes: b"ihk_smp_x86_64.ihk_trampoline\0",
);

// Linux 6.12's Rust `module!` macro cannot emit namespace-import or parameter
// metadata.  These paired records match `MODULE_IMPORT_NS()`,
// `MODULE_PARM_DESC()`, and `module_param()` for loadable and built-in
// configurations.  `modpost` derives the single `depends=ihk` record from the
// provider-anchor relocation above; emitting it here would create a duplicate.
macro_rules! modinfo_pair {
    ($loadable_name:ident, $builtin_name:ident, $loadable:literal, $builtin:literal) => {
        #[cfg(MODULE)]
        #[doc(hidden)]
        #[link_section = ".modinfo"]
        #[used(compiler)]
        static $loadable_name: [u8; $loadable.len()] = *$loadable;

        #[cfg(not(MODULE))]
        #[doc(hidden)]
        #[link_section = ".modinfo"]
        #[used(compiler)]
        static $builtin_name: [u8; $builtin.len()] = *$builtin;
    };
}

modinfo_pair!(
    SMP_IMPORT_NS_MODINFO,
    SMP_BUILTIN_IMPORT_NS_MODINFO,
    b"import_ns=MCKERNEL_IHK_V1\0",
    b"ihk_smp_x86_64.import_ns=MCKERNEL_IHK_V1\0"
);

modinfo_pair!(
    IHK_PHYS_START_PARM_MODINFO,
    IHK_PHYS_START_BUILTIN_PARM_MODINFO,
    b"parm=ihk_phys_start:IHK reserved physical memory start address\0",
    b"ihk_smp_x86_64.parm=ihk_phys_start:IHK reserved physical memory start address\0"
);
modinfo_pair!(
    IHK_PHYS_START_TYPE_MODINFO,
    IHK_PHYS_START_BUILTIN_TYPE_MODINFO,
    b"parmtype=ihk_phys_start:ulong\0",
    b"ihk_smp_x86_64.parmtype=ihk_phys_start:ulong\0"
);
modinfo_pair!(
    IHK_MEM_PARM_MODINFO,
    IHK_MEM_BUILTIN_PARM_MODINFO,
    b"parm=ihk_mem:IHK reserved memory in MBs\0",
    b"ihk_smp_x86_64.parm=ihk_mem:IHK reserved memory in MBs\0"
);
modinfo_pair!(
    IHK_MEM_TYPE_MODINFO,
    IHK_MEM_BUILTIN_TYPE_MODINFO,
    b"parmtype=ihk_mem:ulong\0",
    b"ihk_smp_x86_64.parmtype=ihk_mem:ulong\0"
);
modinfo_pair!(
    IHK_CORES_PARM_MODINFO,
    IHK_CORES_BUILTIN_PARM_MODINFO,
    b"parm=ihk_cores:IHK reserved CPU cores\0",
    b"ihk_smp_x86_64.parm=ihk_cores:IHK reserved CPU cores\0"
);
modinfo_pair!(
    IHK_CORES_TYPE_MODINFO,
    IHK_CORES_BUILTIN_TYPE_MODINFO,
    b"parmtype=ihk_cores:uint\0",
    b"ihk_smp_x86_64.parmtype=ihk_cores:uint\0"
);
modinfo_pair!(
    IHK_START_IRQ_PARM_MODINFO,
    IHK_START_IRQ_BUILTIN_PARM_MODINFO,
    b"parm=ihk_start_irq:IHK IKC IPI to be scanned from this IRQ vector\0",
    b"ihk_smp_x86_64.parm=ihk_start_irq:IHK IKC IPI to be scanned from this IRQ vector\0"
);
modinfo_pair!(
    IHK_START_IRQ_TYPE_MODINFO,
    IHK_START_IRQ_BUILTIN_TYPE_MODINFO,
    b"parmtype=ihk_start_irq:uint\0",
    b"ihk_smp_x86_64.parmtype=ihk_start_irq:uint\0"
);
modinfo_pair!(
    IHK_IKC_IRQ_CORE_PARM_MODINFO,
    IHK_IKC_IRQ_CORE_BUILTIN_PARM_MODINFO,
    b"parm=ihk_ikc_irq_core:Target CPU of IHK IKC IRQ\0",
    b"ihk_smp_x86_64.parm=ihk_ikc_irq_core:Target CPU of IHK IKC IRQ\0"
);
modinfo_pair!(
    IHK_IKC_IRQ_CORE_TYPE_MODINFO,
    IHK_IKC_IRQ_CORE_BUILTIN_TYPE_MODINFO,
    b"parmtype=ihk_ikc_irq_core:uint\0",
    b"ihk_smp_x86_64.parmtype=ihk_ikc_irq_core:uint\0"
);
modinfo_pair!(
    IHK_TRAMPOLINE_PARM_MODINFO,
    IHK_TRAMPOLINE_BUILTIN_PARM_MODINFO,
    b"parm=ihk_trampoline:IHK trampoline page physical address\0",
    b"ihk_smp_x86_64.parm=ihk_trampoline:IHK trampoline page physical address\0"
);
modinfo_pair!(
    IHK_TRAMPOLINE_TYPE_MODINFO,
    IHK_TRAMPOLINE_BUILTIN_TYPE_MODINFO,
    b"parmtype=ihk_trampoline:ulong\0",
    b"ihk_smp_x86_64.parmtype=ihk_trampoline:ulong\0"
);

modinfo_pair!(
    NATIVE_PREPARE_PARM_MODINFO,
    NATIVE_PREPARE_BUILTIN_PARM_MODINFO,
    b"parm=native_boot_prepare_only:Hold owned boot preparation without starting CPUs (0 or 1)\0",
    b"ihk_smp_x86_64.parm=native_boot_prepare_only:Hold owned boot preparation without starting CPUs (0 or 1)\0"
);
modinfo_pair!(
    NATIVE_PREPARE_TYPE_MODINFO,
    NATIVE_PREPARE_BUILTIN_TYPE_MODINFO,
    b"parmtype=native_boot_prepare_only:uint\0",
    b"ihk_smp_x86_64.parmtype=native_boot_prepare_only:uint\0"
);

module! {
    type: IhkSmpModule,
    name: "ihk_smp_x86_64",
    license: "Dual BSD/GPL",
}

struct IhkSmpModule {
    control_device: Option<core::pin::Pin<Box<MiscDeviceRegistration<IhkSmpControlDevice>>>>,
    cpu_controller: Option<smp_cpu::CpuController>,
    memory_controller: Option<smp_memory::MemoryController>,
    provider_lease: Option<ProviderLease>,
}

impl kernel::Module for IhkSmpModule {
    fn init(_module: &'static ThisModule) -> Result<Self> {
        // SAFETY: The provider exports this immutable byte in the declared
        // namespace.  The volatile read keeps the relocation as an actual
        // module dependency; the value itself has no behavioral meaning.
        let _ = unsafe { core::ptr::read_volatile(core::ptr::addr_of!(IHK_PROVIDER_LIFECYCLE_V1)) };
        // Publish the provider before misc_register makes /dev/mcd0 visible.
        // If registration fails, this local non-Copy lease drops and rolls the
        // provider publication back before module initialization returns.
        let provider_lease = ProviderLease::attach()?;
        let cpu_controller = smp_cpu::CpuController::new()?;
        let memory_controller = smp_memory::MemoryController::new()?;
        let control_device = Box::pin_init(
            MiscDeviceRegistration::<IhkSmpControlDevice>::register(MiscDeviceOptions {
                name: c_str!("mcd0"),
            }),
            GFP_KERNEL,
        )?;
        pr_info!(
            "lifecycle=load parameters={} dependency={} import_namespace={}\n",
            IHK_SMP_PARAMETER_COUNT,
            IHK_SMP_DEPENDENCY,
            IHK_SMP_IMPORT_NAMESPACE,
        );
        Ok(Self {
            control_device: Some(control_device),
            cpu_controller: Some(cpu_controller),
            memory_controller: Some(memory_controller),
            provider_lease: Some(provider_lease),
        })
    }
}

impl Drop for IhkSmpModule {
    fn drop(&mut self) {
        drop(self.control_device.take());
        drop(self.memory_controller.take());
        drop(self.cpu_controller.take());
        drop(self.provider_lease.take());
        pr_info!(
            "lifecycle=unload parameters={} dependency={} import_namespace={}\n",
            IHK_SMP_PARAMETER_COUNT,
            IHK_SMP_DEPENDENCY,
            IHK_SMP_IMPORT_NAMESPACE,
        );
    }
}
