# Native Rust-for-Linux production objects. Do not add project C objects here.
obj-$(CONFIG_MCKERNEL_RUST_IHK) += ihk.o
obj-$(CONFIG_MCKERNEL_RUST_IHK_SMP_X86_64) += ihk_smp_x86_64.o
obj-$(CONFIG_MCKERNEL_RUST_MCCTRL) += mcctrl.o
