/* Independent C finite model; it does not include Rust or production headers. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define INV_MAX 8u
#define INV_PAGE 4096ull
enum inventory_status { REF_OK = 0, REF_EINVAL = -22, REF_EOVERFLOW = -75, REF_ENOSPC = -28 };
struct descriptor { uint64_t id, physical_start, page_count, next, prev; uint32_t generation; uint8_t mode; };
struct inventory_case { const char *name; struct descriptor records[INV_MAX]; uint64_t ids[INV_MAX]; unsigned record_count, selected, capacity; uint64_t claimed, physical_base, physical_limit, epoch, observed; };
static const struct descriptor *resolve(const struct inventory_case *c, uint64_t id) { unsigned i; for (i = 0; i < c->record_count; ++i) if (c->records[i].id == id) return &c->records[i]; return 0; }
static int checked_bytes(uint64_t pages, uint64_t *bytes) { if (!pages) return REF_EINVAL; if (__builtin_mul_overflow(pages, INV_PAGE, bytes)) return REF_EOVERFLOW; return REF_OK; }
static uint64_t state_hash(const struct inventory_case *c) { uint64_t hash = 0xcbf29ce484222325ull; unsigned i; const struct descriptor *d;
#define MIX(V) do { hash ^= (uint64_t)(V); hash *= 0x100000001b3ull; } while (0)
 for (i = 0; i < c->record_count; ++i) { d = &c->records[i]; MIX(d->id); MIX(d->physical_start); MIX(d->page_count); MIX(d->generation); MIX(d->mode); MIX(d->next); MIX(d->prev); }
#undef MIX
 return hash; }
/* Validates only immutable case bytes. It allocates nothing and invokes no callback/release path. */
static int validate(const struct inventory_case *c) { const struct descriptor *sentinel, *d, *prior; uint64_t count_plus_sentinel, bytes, end, prior_bytes, prior_end; unsigned i, j, sentinel_count = 0;
 if (!c || c->record_count < 2 || c->record_count > INV_MAX || c->physical_base % INV_PAGE || c->physical_limit % INV_PAGE || c->physical_base >= c->physical_limit) return REF_EINVAL;
 if (__builtin_add_overflow(c->claimed, 1ull, &count_plus_sentinel)) return REF_EOVERFLOW;
 if (!c->claimed || c->claimed > INV_MAX || c->claimed != c->selected || count_plus_sentinel != c->record_count) return REF_EINVAL;
 for (i = 0; i < c->record_count; ++i) { if (!c->records[i].id) return REF_EINVAL; if (c->records[i].id == 1) ++sentinel_count; for (j = 0; j < i; ++j) if (c->records[i].id == c->records[j].id) return REF_EINVAL; }
 if (sentinel_count != 1) return REF_EINVAL; sentinel = resolve(c, 1);
 if (!sentinel || !sentinel->next || !sentinel->prev || sentinel->next == 1 || sentinel->prev == 1 || sentinel->next != c->ids[0] || sentinel->prev != c->ids[c->selected - 1]) return REF_EINVAL;
 for (i = 0; i < c->selected; ++i) { uint64_t expected_prev = i ? c->ids[i - 1] : 1, expected_next = i + 1 == c->selected ? 1 : c->ids[i + 1];
  if (!c->ids[i] || c->ids[i] == 1) return REF_EINVAL; for (j = 0; j < i; ++j) if (c->ids[i] == c->ids[j]) return REF_EINVAL; d = resolve(c, c->ids[i]);
  if (!d || d->generation != 7 || d->mode != 1 || d->prev != expected_prev || d->next != expected_next) return REF_EINVAL;
  if (checked_bytes(d->page_count, &bytes) != REF_OK) return checked_bytes(d->page_count, &bytes); if (__builtin_add_overflow(d->physical_start, bytes, &end)) return REF_EOVERFLOW;
  if (d->physical_start % INV_PAGE || d->physical_start < c->physical_base || end > c->physical_limit) return REF_EINVAL;
  for (j = 0; j < i; ++j) { prior = resolve(c, c->ids[j]); if (!prior) return REF_EINVAL; if (checked_bytes(prior->page_count, &prior_bytes) != REF_OK) return checked_bytes(prior->page_count, &prior_bytes); if (__builtin_add_overflow(prior->physical_start, prior_bytes, &prior_end)) return REF_EOVERFLOW; if (prior->physical_start < end && d->physical_start < prior_end) return REF_EINVAL; }
 }
 return REF_OK; }
static void put(struct descriptor *d, uint64_t id, uint64_t start, uint64_t pages, uint32_t generation, uint8_t mode, uint64_t next, uint64_t prev) { d->id = id; d->physical_start = start; d->page_count = pages; d->generation = generation; d->mode = mode; d->next = next; d->prev = prev; }
static int construct_case(const char *name, struct inventory_case *c) { int two = !strcmp(name, "capacity-exceeded") || !strcmp(name, "count-mismatch") || !strcmp(name, "overlapping-extent") || !strcmp(name, "foreign-cycle") || !strcmp(name, "valid-two");
 memset(c, 0, sizeof(*c)); c->name = name; c->record_count = two ? 3u : 2u; c->selected = two ? 2u : 1u; c->capacity = c->selected; c->claimed = c->selected; c->physical_base = 0x1000; c->physical_limit = 0x9000; c->epoch = c->observed = 9;
 put(&c->records[0], 1, 0, 0, 0, 0, 2, two ? 3 : 2); put(&c->records[1], 2, 0x1000, 1, 7, 1, two ? 3 : 1, 1); if (two) put(&c->records[2], 3, 0x3000, 1, 7, 1, 1, 2); c->ids[0] = 2; if (two) c->ids[1] = 3;
 if (!strcmp(name, "empty")) { c->selected = 0; c->claimed = 0; } else if (!strcmp(name, "capacity-zero")) c->capacity = 0; else if (!strcmp(name, "capacity-exceeded")) c->capacity = 1; else if (!strcmp(name, "count-mismatch")) { c->selected = 1; c->claimed = 1; } else if (!strcmp(name, "count-overflow")) c->claimed = UINT64_MAX; else if (!strcmp(name, "duplicate-id")) c->records[1].id = 1; else if (!strcmp(name, "foreign-id")) c->ids[0] = 99; else if (!strcmp(name, "null-link")) c->records[1].next = 0; else if (!strcmp(name, "dangling-link")) c->records[1].next = 99; else if (!strcmp(name, "one-sided-link")) c->records[1].prev = 2; else if (!strcmp(name, "malformed-sentinel")) c->records[0].next = 1; else if (!strcmp(name, "foreign-cycle")) c->records[2].next = 2; else if (!strcmp(name, "wrong-mode")) c->records[1].mode = 0; else if (!strcmp(name, "invalid-page-count")) c->records[1].page_count = 0; else if (!strcmp(name, "page-count-overflow")) c->records[1].page_count = UINT64_MAX; else if (!strcmp(name, "misaligned-extent")) c->records[1].physical_start = 0x1001; else if (!strcmp(name, "foreign-extent")) c->records[1].physical_start = 0x9000; else if (!strcmp(name, "overlapping-extent")) c->records[2].physical_start = 0x1000; else if (!strcmp(name, "stale-generation")) c->records[1].generation = 8; else if (!strcmp(name, "concurrent-mutation")) c->observed = 8; else if (strcmp(name, "capacity-exact") && strcmp(name, "valid-single") && strcmp(name, "valid-two")) return REF_EINVAL; return REF_OK; }
static int run_case(const char *name, uint64_t *before_out, uint64_t *after_out) { struct inventory_case c; uint64_t before; unsigned i; uint64_t pushed[INV_MAX]; unsigned pushed_count = 0; int status = construct_case(name, &c); if (status != REF_OK) return status; before = state_hash(&c); if (c.observed != c.epoch) status = REF_EINVAL; else { status = REF_OK; for (i = 0; i < c.selected; ++i) { if (pushed_count >= c.capacity) { status = REF_ENOSPC; break; } if (!c.ids[i] || c.ids[i] == 1 || !resolve(&c, c.ids[i])) { status = REF_EINVAL; break; } pushed[pushed_count++] = c.ids[i]; } if (status == REF_OK) status = validate(&c); } (void)pushed; *before_out = before; *after_out = state_hash(&c); if (before != *after_out) return REF_EINVAL; return status; }
static int expected_status(const char *name) { if (!strcmp(name, "capacity-zero") || !strcmp(name, "capacity-exceeded")) return REF_ENOSPC; if (!strcmp(name, "count-overflow") || !strcmp(name, "page-count-overflow")) return REF_EOVERFLOW; if (!strcmp(name, "empty") || !strcmp(name, "count-mismatch") || !strcmp(name, "duplicate-id") || !strcmp(name, "foreign-id") || !strcmp(name, "null-link") || !strcmp(name, "dangling-link") || !strcmp(name, "one-sided-link") || !strcmp(name, "malformed-sentinel") || !strcmp(name, "foreign-cycle") || !strcmp(name, "wrong-mode") || !strcmp(name, "invalid-page-count") || !strcmp(name, "misaligned-extent") || !strcmp(name, "foreign-extent") || !strcmp(name, "overlapping-extent") || !strcmp(name, "stale-generation") || !strcmp(name, "concurrent-mutation")) return REF_EINVAL; if (!strcmp(name, "capacity-exact") || !strcmp(name, "valid-single") || !strcmp(name, "valid-two")) return REF_OK; return 1; }
int main(int argc, char **argv) { int expected, actual; uint64_t before, after; if (argc != 2) return 2; expected = expected_status(argv[1]); if (expected == 1) return 2; actual = run_case(argv[1], &before, &after); if (actual != expected || before != after) return 1; printf("%s|%d|%016llx|%016llx\n", argv[1], actual, (unsigned long long)before, (unsigned long long)after); return 0; }
