#!/usr/bin/env python3
"""Render the McKernel autonomous campaign's human-readable progress dashboard."""
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TRACKER_DIR = ROOT / "docs/verification/os-milestones-20260914"


def read_json(path: Path, default):
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return default


def bar(done: int, total: int, width: int = 24) -> str:
    if not total:
        return "[" + "?" * width + "] n/a"
    filled = max(0, min(width, round(width * done / total)))
    percent = 100.0 * done / total
    return "[" + "#" * filled + "." * (width - filled) + "] " + f"{percent:.1f}% ({done}/{total})"


def current_value(text: str, pattern: str, fallback: str) -> str:
    match = re.search(pattern, text, re.IGNORECASE)
    return match.group(1) if match else fallback


def status_word(state: dict) -> str:
    if state.get("phase") == "stopped":
        return "STOPPED (resume is operator-controlled)"
    if state.get("phase") == "running":
        return "RUNNING"
    return str(state.get("phase") or state.get("status") or "UNKNOWN").upper()


def render() -> str:
    state = read_json(ROOT / ".git/os-autopilot/state.json", {})
    watcher = read_json(ROOT / ".git/os-autopilot/watcher.json", {})
    gate_map = read_json(TRACKER_DIR / "gate-map.json", {})
    tasks_doc = read_json(TRACKER_DIR / "tasks.json", {})
    current_path = TRACKER_DIR / "CURRENT.md"
    current = current_path.read_text(errors="replace") if current_path.exists() else ""
    status_counts = gate_map.get("status_counts", {})
    passed = int(status_counts.get("PASS", 0))
    in_progress = int(status_counts.get("IN_PROGRESS", 0))
    gates = int(gate_map.get("native_gate_count", 0))
    points = int(gate_map.get("earned_points", 0))
    total_points = int(gate_map.get("total_points", 0))
    task_count = len(tasks_doc.get("tasks", []))
    last_update = state.get("heartbeat_at") or state.get("updated_at") or watcher.get("heartbeat_utc") or "unknown"
    refreshed = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    application_cases = current_value(current, r"(\d+/\d+) application cases accepted", "0/273")
    fault_modes = current_value(current, r"(\d+/\d+) narrow fault modes accepted", "2/4")
    language_gates = current_value(current, r"(\d+/\d+) language gates", "0/7")
    phase_rows = [
        ("S1", "Trustworthy execution lane", "accepted source, native, root, guest, cleanup and comparison evidence", "ACTIVE", "M02-B root-positive infrastructure is accepted; adverse/native/guest closure remains open"),
        ("S2", "Kernel and runtime closure", "VM, pending-free, lifecycle, transport, shutdown and failure ownership", "NEXT", "M03-A/B, M02-C..F and runtime ownership still require executable proof"),
        ("S3", "Application acceptance", "all catalog cases, application oracles, fault modes and integration", "NOT STARTED", "0/273 application cases are accepted; three compiled cases do not count"),
        ("S4", "Platform and release qualification", "language gates, Rocky package, hardware, performance and independent release", "NOT STARTED", "0/7 language gates; platform and release gates remain downstream"),
    ]
    lines = [
        "# McKernel Progress Dashboard",
        "",
        "> Generated by `scripts/update_progress_tracker.py`. This is a progress view, not acceptance authority.",
        "> Evidence and completion remain governed by `gate-map.json`, the task contracts, and `CURRENT.md`.",
        "",
        "## Snapshot",
        "",
        f"- Dashboard refreshed: `{refreshed}`",
        f"- Launcher state heartbeat: `{last_update}`",
        f"- Launcher: **{status_word(state)}**; phase `{state.get('phase', 'unknown')}`; stop reason `{state.get('stop_reason') or 'none'}`",
        f"- Worker PID: `{state.get('worker_pid') or 'none'}`; server PID: `{state.get('server_pid') or 'none'}`",
        f"- Run directory: `{state.get('run_dir') or state.get('log_dir') or 'not recorded'}`",
        "",
        "## Acceptance Bars",
        "",
        f"- Native production gates: `{bar(passed, gates)}`; `{in_progress}` additional gate(s) in progress; `{gates - passed - in_progress}` TODO.",
        f"- Earned contractual points: `{bar(points, total_points)}`.",
        f"- Planned dispatcher task packets: `{bar(0, task_count)}`; plan status is intentionally not acceptance status.",
        f"- Application catalog: `{application_cases}` accepted.",
        f"- Narrow fault modes: `{fault_modes}` accepted.",
        f"- Language gates: `{language_gates}` accepted.",
        "",
        "## Intermediary Goal Ladder",
        "",
        "| ID | Goal | Exit condition | Status | Current evidence / gap |",
        "| --- | --- | --- | --- | --- |",
    ]
    for ident, goal, exit_condition, status, note in phase_rows:
        lines.append(f"| {ident} | {goal} | {exit_condition} | **{status}** | {note} |")
    lines += [
        "",
        "## Detailed Work Queue",
        "",
        "| Track | Current target | Required proof before the bar moves | State | Next action |",
        "| --- | --- | --- | --- | --- |",
        "| M00 | durable ledger, preserved work, resource policy | exact source/evidence identity and fetched checkpoint | mostly accepted | keep ledger and tracker synchronized at every checkpoint |",
        "| M01 | all four published-response fault modes | source contract plus executable native/root/guest comparison | partial | finish fault-mode matrix and retain negative controls |",
        "| M02 | Linux/McKernel execution and comparison | root-positive, adverse, native collector, guest terminal and cleanup receipts | partial | continue M02-C through M02-F after the accepted root-positive packet |",
        "| M03 | pending-free, invalidation and safe admission | real Rust/C boundary execution, invalid input preservation, reuse and pressure evidence | open | replace rejected candidate with a reviewed runnable packet |",
        "| M04-M07 | application, shutdown, syscall, vector and failure behavior | applicable catalog cases with exact oracle and production integration | open | expand only after execution lane contracts are trustworthy |",
        "| M08-M09 | native Rust and executable closure | clean build, load, runtime, unload and assembly evidence | open | preserve source review, then schedule native qualification |",
        "| M10-M13 | Rocky, integration, hardware/performance and release | reproducible package/runtime/benchmark/release evidence | downstream | do not claim complete from local source progress |",
        "",
        "## Current Blockers",
        "",
        f"- `{state.get('stop_reason') or 'none'}`: launcher state is currently `{state.get('phase', 'unknown')}`.",
        "- The OS objective is not complete: source review and infrastructure packets are not substitutes for native, guest, application, language, platform or release proof.",
        "- The heavy build/guest lease and free-space policy must be checked immediately before every expensive run.",
        "- External hardware, hosted CI, and platform-specific acceptance remain later gates even when local preparation is complete.",
        "",
        "## Checkpoint Protocol",
        "",
        "1. Run `python3 scripts/update_progress_tracker.py` after every accepted packet, diagnosis, or launcher checkpoint.",
        "2. Record the exact evidence path, source revision, test command, result, blocker, and next action in `CURRENT.md`.",
        "3. Commit and push the tracker together with the verified checkpoint; never inflate a bar for source-only or rejected work.",
        "4. Watch this file with `watch -n 15 sed -n '1,220p' docs/verification/os-milestones-20260914/PROGRESS.md`.",
        "",
        "## Source Of Truth",
        "",
        "- `docs/verification/os-milestones-20260914/gate-map.json` - contractual gate and point counts.",
        "- `docs/verification/os-milestones-20260914/tasks.json` - 68 planned task packets and dependencies.",
        "- `docs/verification/os-milestones-20260914/CURRENT.md` - detailed chronological evidence cursor.",
        "- `.git/os-autopilot/state.json` - launcher-owned runtime state; do not edit by hand.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=TRACKER_DIR / "PROGRESS.md")
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render())
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
