if (NOT DEFINED CMD_FILE)
	message(FATAL_ERROR "CMD_FILE is required")
endif()
if (NOT DEFINED OBJ_FILE)
	message(FATAL_ERROR "OBJ_FILE is required")
endif()
if (NOT DEFINED SRC_FILE)
	message(FATAL_ERROR "SRC_FILE is required")
endif()
if (NOT DEFINED RUSTC)
	set(RUSTC "rustc")
endif()

file(WRITE "${CMD_FILE}" "cmd_${OBJ_FILE} := ${RUSTC} --emit=obj=${OBJ_FILE} ${SRC_FILE}\n\n")
file(APPEND "${CMD_FILE}" "source_${OBJ_FILE} := ${SRC_FILE}\n\n")
file(APPEND "${CMD_FILE}" "deps_${OBJ_FILE} := \\\n  ${SRC_FILE}\n\n")
file(APPEND "${CMD_FILE}" "${OBJ_FILE}: $(deps_${OBJ_FILE})\n\n")
file(APPEND "${CMD_FILE}" "$(deps_${OBJ_FILE}):\n")
